"""Step 9: Telegram bot (interactive, long-running)."""

from __future__ import annotations

import textwrap

from ..constants import BOT_SCRIPT, BOT_SERVICE, BOT_VENV
from ..services import (
    daemon_reload,
    disable_unit,
    enable_unit,
    start_unit,
    stop_unit,
    unit_status,
    write_unit,
)
from ..utils import file_exists_sudo, run, write_file_sudo
from .base import Step, StepResult


class TelegramBotStep(Step):
    name = "telegram_bot"
    label = "Install Telegram Bot"
    description = "Deploy the interactive Telegram bot as a systemd service"
    depends_on = ["restic_s3"]

    def run(self) -> StepResult:
        token = self.cfg.telegram_bot_token
        chat_id = self.cfg.telegram_chat_id
        if not token or not chat_id:
            return StepResult(self.name, False, "Telegram token/chat_id not configured")

        # Create venv + install deps
        self.log("Creating bot virtualenv...")
        run(f"python3 -m venv {BOT_VENV}", sudo=True, dry_run=self.dry_run)
        r = run(
            f"{BOT_VENV}/bin/pip install --quiet "
            "python-telegram-bot APScheduler requests",
            sudo=True, dry_run=self.dry_run, timeout=300,
        )
        if not r.ok and not self.dry_run:
            return StepResult(self.name, False, f"pip install failed: {r.stderr}", r.stderr)

        # Write bot script
        self._write_bot_script()

        # Write systemd unit
        unit = textwrap.dedent(f"""\
            [Unit]
            Description=Nextcloud Telegram Bot
            After=network-online.target docker.service
            Wants=network-online.target

            [Service]
            Type=simple
            User=root
            WorkingDirectory=/opt
            ExecStart={BOT_VENV}/bin/python3 {BOT_SCRIPT}
            Restart=always
            RestartSec=10
            StandardOutput=journal
            StandardError=journal

            [Install]
            WantedBy=multi-user.target
        """)
        write_unit(BOT_SERVICE, unit, dry_run=self.dry_run)
        daemon_reload(dry_run=self.dry_run)
        enable_unit("ncbot", dry_run=self.dry_run)
        start_unit("ncbot", dry_run=self.dry_run)

        self.mark_done({"token_set": True, "chat_id": chat_id})
        return StepResult(
            self.name, True,
            "Telegram bot installed and started",
            "Send /start to your bot in Telegram to verify. Daily report at 08:00.",
        )

    def _write_bot_script(self) -> None:
        """Write the full interactive bot script (from the guide)."""
        script = self._bot_template()
        if self.dry_run:
            self.log(f"[dry-run] would write {BOT_SCRIPT}")
            return
        write_file_sudo(BOT_SCRIPT, script, mode=0o755)
        self.log(f"Wrote {BOT_SCRIPT}")

    def _bot_template(self) -> str:
        return textwrap.dedent(f'''\
            #!/usr/bin/env python3
            """Nextcloud Telegram Bot — daily reports + on-demand commands.
            Generated by homecloud installer.
            """

            import os, re, subprocess, json, logging
            from datetime import datetime
            import requests
            from telegram import Update, BotCommand
            from telegram.ext import Application, CommandHandler, ContextTypes
            from apscheduler.schedulers.asyncio import AsyncIOScheduler

            TELEGRAM_TOKEN = "{self.cfg.telegram_bot_token}"
            CHAT_ID = "{self.cfg.telegram_chat_id}"
            NC_DOMAIN = "{self.cfg.nextcloud_url}"
            NC_TOKEN = ""
            BACKUP_LOG = "/var/log/nextcloud-s3-backup.log"
            NC_DATA_PATH = "/mnt/ncdata/nextcloud"
            RESTIC_REPO = "{self.cfg.restic_repository}"
            AWS_KEY = "{self.cfg.aws_access_key_id}"
            AWS_SECRET = "{self.cfg.aws_secret_access_key}"
            RESTIC_PASSWORD = "{self.cfg.restic_password}"

            logging.basicConfig(level=logging.INFO)
            logger = logging.getLogger(__name__)

            def bytes_to_human(b):
                try: b = int(b)
                except: return str(b)
                for u in ["B","KB","MB","GB","TB"]:
                    if b < 1024: return f"{{b:.1f}} {{u}}"
                    b /= 1024
                return f"{{b:.1f}} PB"

            def run(cmd):
                try:
                    return subprocess.check_output(cmd, shell=True, stderr=subprocess.DEVNULL, text=True).strip()
                except: return "N/A"

            def occ(command):
                return run(f"docker exec --user www-data nextcloud-aio-nextcloud php occ {{command}}")

            def get_nc_api():
                try:
                    r = requests.get(
                        f"{{NC_DOMAIN}}/ocs/v2.php/apps/serverinfo/api/v1/info?format=json",
                        headers={{"NC-Token": NC_TOKEN, "OCS-APIRequest": "true"}},
                        timeout=15,
                    )
                    return r.json()["ocs"]["data"]
                except Exception as e:
                    logger.error(f"NC API error: {{e}}")
                    return None

            def parse_backup_log():
                result = {{"last_run": "Never", "status": "Unknown", "uploaded": "N/A", "duration": "N/A"}}
                if not os.path.exists(BACKUP_LOG): return result
                with open(BACKUP_LOG) as f: lines = f.readlines()
                starts = [i for i,l in enumerate(lines) if "=== Backup started" in l]
                ends = [i for i,l in enumerate(lines) if "=== Backup finished" in l]
                if starts: result["last_run"] = lines[starts[-1]].replace("=== Backup started: ","").strip()
                errors = [l for l in lines[starts[-1]:] if "error" in l.lower()] if starts else []
                result["status"] = "❌ Error" if errors else "✅ Success"
                for line in reversed(lines):
                    if "Added to the repo" in line:
                        m = re.search(r"Added to the repo.*?:\\s*(.+)", line)
                        if m: result["uploaded"] = m.group(1).strip()
                        break
                return result

            def get_restic_snapshots():
                env = {{**os.environ, "AWS_ACCESS_KEY_ID": AWS_KEY,
                        "AWS_SECRET_ACCESS_KEY": AWS_SECRET,
                        "RESTIC_PASSWORD": RESTIC_PASSWORD,
                        "RESTIC_REPOSITORY": RESTIC_REPO}}
                try:
                    out = subprocess.check_output(
                        ["restic", "snapshots", "--compact", "--last", "5"],
                        env=env, stderr=subprocess.DEVNULL, text=True, timeout=30)
                    return out.strip()
                except: return "Could not reach S3 (Glacier restore may be needed)"

            def build_quick_status():
                uptime = run("uptime -p")
                cpu_temp = run("vcgencmd measure_temp | cut -d= -f2")
                mem = run("free -h | awk '/^Mem:/ {{print $3\"/\"$2}}'")
                cpu = run("top -bn1 | grep 'Cpu' | awk '{{print $2}}' | cut -d% -f1")
                ssd = run("df -h /mnt/ncdata | awk 'NR==2 {{print $3\"/\"$2\" (\"$5\")\"}}'")
                nc_status = run("docker inspect --format='{{{{.State.Status}}}}' nextcloud-aio-nextcloud 2>/dev/null")
                bk = parse_backup_log()
                return (
                    f"⚡ *Quick Status*\\n"
                    f"🕐 {{datetime.now().strftime('%d %b %Y %H:%M')}}\\n\\n"
                    f"🖥 CPU: `{{cpu}}%` load | `{{cpu_temp}}` temp\\n"
                    f"🧠 RAM: `{{mem}}`\\n"
                    f"💾 SSD: `{{ssd}}`\\n"
                    f"☁️ Nextcloud: `{{nc_status}}`\\n\\n"
                    f"📦 Last backup: `{{bk['last_run']}}`\\n"
                    f"   Status: {{bk['status']}} | Uploaded: `{{bk['uploaded']}}`"
                )

            def build_daily_report():
                data = get_nc_api()
                bk = parse_backup_log()
                uptime = run("uptime -p")
                cpu_temp = run("vcgencmd measure_temp | cut -d= -f2")
                mem = run("free -h | awk '/^Mem:/ {{print $3\"/\"$2}}'")
                cpu = run("top -bn1 | grep 'Cpu' | awk '{{print $2}}' | cut -d% -f1")
                ssd = run("df -h /mnt/ncdata | awk 'NR==2 {{print $3\"/\"$2\" (\"$5\")\"}}'")
                sd = run("df -h / | awk 'NR==2 {{print $3\"/\"$2\" (\"$5\")\"}}'")
                nc_block = "❌ NC API unavailable"
                if data:
                    nc_block = (
                        f"*Nextcloud*\\n"
                        f"• Files: `{{data.get('nextcloud',{{}}).get('storage',{{}}).get('num_files','?')}}`\\n"
                        f"• Free: `{{bytes_to_human(data.get('nextcloud',{{}}).get('system',{{}}).get('freespace',0))}}`\\n"
                        f"• DB: `{{bytes_to_human(data.get('server',{{}}).get('database',{{}}).get('size',0))}}`"
                    )
                return (
                    f"📊 *Nextcloud Daily Report*\\n"
                    f"📅 {{datetime.now().strftime('%A, %d %b %Y %H:%M')}}\\n\\n"
                    f"🏠 *System*\\n• Uptime: `{{uptime}}`\\n• CPU: `{{cpu}}%` | Temp: `{{cpu_temp}}`\\n"
                    f"• RAM: `{{mem}}`\\n• SSD: `{{ssd}}`\\n• SD: `{{sd}}`\\n\\n"
                    f"☁️ {{nc_block}}\\n\\n"
                    f"📦 *Backup*\\n• Last: `{{bk['last_run']}}`\\n• Status: {{bk['status']}}\\n"
                    f"• Uploaded: `{{bk['uploaded']}}`"
                )

            def build_backup_report():
                bk = parse_backup_log()
                snaps = get_restic_snapshots()
                tail = run(f"tail -20 {{BACKUP_LOG}} 2>/dev/null") or "No log yet"
                return (
                    f"📦 *Backup Deep Dive*\\n📅 {{datetime.now().strftime('%d %b %Y %H:%M')}}\\n\\n"
                    f"• Last run: `{{bk['last_run']}}`\\n• Status: {{bk['status']}}\\n"
                    f"• Uploaded: `{{bk['uploaded']}}`\\n\\n"
                    f"🗂 *S3 Snapshots*\\n````{{snaps}}````\\n\\n"
                    f"📋 *Log tail*\\n````{{tail[-600:]}}````"
                )
            def build_users_report():
                """Per-user storage usage via occ usage-report:generate."""
                report = occ("usage-report:generate --output-format=json 2>/dev/null")
                if not report or report == "N/A":
                    # Fallback: list users + their quota usage
                    users_raw = occ("user:list --output=json 2>/dev/null")
                    if users_raw and users_raw != "N/A":
                        try:
                            users = json.loads(users_raw)
                            lines = [f"• `{{u}}`" for u in users]
                            return f"👥 *Users (no usage-report app)*\\n" + "\\n".join(lines[:30])
                        except Exception:
                            pass
                    return "❌ Could not fetch user usage. Install the 'usage_report' app in Nextcloud."
                try:
                    data = json.loads(report)
                except Exception:
                    return f"````{{report[:1000]}}````"
                lines = []
                for entry in data:
                    uid = entry.get("user_id", "?")
                    used = bytes_to_human(entry.get("storage_usage", 0) * 1024)
                    quota = entry.get("storage_quota", 0)
                    quota_str = bytes_to_human(quota * 1024) if quota and quota > 0 else "unlimited"
                    last_login = entry.get("last_login", "never")
                    if last_login and last_login != "never":
                        last_login = last_login[:10]
                    lines.append(f"• `{{uid}}`: {{used}} / {{quota_str}} (last login: {{last_login}})")
                return (
                    f"👥 *Per-User Usage*\\n📅 {{datetime.now().strftime('%d %b %Y %H:%M')}}\\n\\n"
                    + "\\n".join(lines[:40])
                )
            async def cmd_start(update, ctx):
                await update.message.reply_text(
                    "👋 *Nextcloud Bot Online!*\\n\\n"
                    "/status — quick health check\\n"
                    "/report — full daily report\\n"                    "/users — per-user storage usage\\n"                    "/backup — backup status + S3 snapshots\\n"
                    "/runbackup — trigger a backup NOW\\n"
                    "/logs — last 30 lines of backup log\\n"
                    "/help — show this menu",
                    parse_mode="Markdown")

            async def cmd_status(update, ctx):
                await update.message.reply_text("⏳ Fetching...")
                await update.message.reply_text(build_quick_status(), parse_mode="Markdown")

            async def cmd_report(update, ctx):
                await update.message.reply_text("⏳ Building report...")
                await update.message.reply_text(build_daily_report(), parse_mode="Markdown")

            async def cmd_backup(update, ctx):
                await update.message.reply_text("⏳ Fetching backup details...")
                await update.message.reply_text(build_backup_report(), parse_mode="Markdown")

            async def cmd_users(update, ctx):
                await update.message.reply_text("⏳ Fetching per-user usage...")
                await update.message.reply_text(build_users_report(), parse_mode="Markdown")

            async def cmd_runbackup(update, ctx):
                await update.message.reply_text("🚀 Triggering backup now...")
                subprocess.Popen(["/opt/nextcloud-s3-backup.sh"],
                    stdout=open(BACKUP_LOG, "a"), stderr=subprocess.STDOUT)
                await update.message.reply_text("✅ Backup started! Check /backup in ~5 min.")

            async def cmd_logs(update, ctx):
                log = run(f"tail -30 {{BACKUP_LOG}} 2>/dev/null") or "No log file yet"
                await update.message.reply_text(f"📋 *Log*\\n````{{log[-2000:]}}````", parse_mode="Markdown")

            async def cmd_help(update, ctx):
                await cmd_start(update, ctx)

            async def send_daily_report(app):
                try:
                    await app.bot.send_message(chat_id=CHAT_ID, text=build_daily_report(), parse_mode="Markdown")
                except Exception as e:
                    logger.error(f"Daily report failed: {{e}}")

            def main():
                app = Application.builder().token(TELEGRAM_TOKEN).build()
                app.add_handler(CommandHandler("start", cmd_start))
                app.add_handler(CommandHandler("status", cmd_status))
                app.add_handler(CommandHandler("report", cmd_report))
                app.add_handler(CommandHandler("users", cmd_users))
                app.add_handler(CommandHandler("backup", cmd_backup))
                app.add_handler(CommandHandler("runbackup", cmd_runbackup))
                app.add_handler(CommandHandler("logs", cmd_logs))
                app.add_handler(CommandHandler("help", cmd_help))

                async def post_init(application):
                    await application.bot.set_my_commands([
                        BotCommand("status", "⚡ Quick health check"),
                        BotCommand("report", "📊 Full daily report"),
                        BotCommand("users", "👥 Per-user storage usage"),
                        BotCommand("backup", "📦 Backup + S3 snapshots"),
                        BotCommand("runbackup", "🚀 Trigger backup now"),
                        BotCommand("logs", "📋 View backup log"),
                        BotCommand("help", "❓ Show all commands"),
                    ])
                    scheduler = AsyncIOScheduler(timezone="{self.cfg.timezone}")
                    scheduler.add_job(send_daily_report, trigger="cron", hour=8, minute=0, args=[application])
                    scheduler.start()

                app.post_init = post_init
                app.run_polling(allowed_updates=Update.ALL_TYPES)

            if __name__ == "__main__":
                main()
            ''')

    def status(self) -> StepResult:
        if self.dry_run:
            return StepResult(self.name, True, "[dry-run]")
        st = unit_status("ncbot")
        return StepResult(self.name, st == "active", f"ncbot: {st}")

    def repair(self) -> StepResult:
        self.log("Restarting bot service...")
        start_unit("ncbot", dry_run=self.dry_run)
        return self.status()

    def undo(self) -> StepResult:
        self.log("Conservative undo: stopping + disabling bot (script kept)")
        stop_unit("ncbot", dry_run=self.dry_run)
        disable_unit("ncbot", dry_run=self.dry_run)
        if not self.dry_run and file_exists_sudo(BOT_SERVICE):
            run(f"sudo -n rm -f {BOT_SERVICE}", capture=True)
            daemon_reload(dry_run=self.dry_run)
        self.mark_undone()
        return StepResult(self.name, True, "Bot service removed (script kept at /opt/ncbot.py)")
