"""Step 9: Telegram bot (interactive, long-running).

The bot queries the Immich REST API for storage stats, job status, and
triggers jobs. Unlike Nextcloud (which had `occ`), Immich has no CLI — all
admin actions go through the REST API with an API key generated in the web
UI. So the bot requires `immich_api_key` to be set in config (manual post-
install step).
"""

from __future__ import annotations

import textwrap

from ..constants import BOT_SCRIPT, BOT_SERVICE, BOT_SERVICE_NAME, BOT_VENV
from ..services import (
    daemon_reload,
    disable_unit,
    enable_unit,
    start_unit,
    stop_unit,
    unit_status,
    write_unit,
)
from ..utils import file_exists_sudo, run, write_file_sudo
from .base import Step, StepResult


class TelegramBotStep(Step):
    name = "telegram_bot"
    label = "Install Telegram Bot"
    description = "Deploy the interactive Telegram bot as a systemd service"
    depends_on = ["restic_s3"]

    def run(self) -> StepResult:
        token = self.cfg.telegram_bot_token
        chat_id = self.cfg.telegram_chat_id
        if not token or not chat_id:
            return StepResult(self.name, False, "Telegram token/chat_id not configured")

        # Create venv + install deps
        self.log("Creating bot virtualenv...")
        run(f"python3 -m venv {BOT_VENV}", sudo=True, dry_run=self.dry_run)
        r = run(
            f"{BOT_VENV}/bin/pip install --quiet "
            "python-telegram-bot APScheduler requests",
            sudo=True, dry_run=self.dry_run, timeout=300,
        )
        if not r.ok and not self.dry_run:
            return StepResult(self.name, False, f"pip install failed: {r.stderr}", r.stderr)

        # Write bot script
        self._write_bot_script()

        # Write systemd unit
        unit = textwrap.dedent(f"""\
            [Unit]
            Description=Home Cloud Telegram Bot (Immich)
            After=network-online.target docker.service
            Wants=network-online.target

            [Service]
            Type=simple
            User=root
            WorkingDirectory=/opt
            ExecStart={BOT_VENV}/bin/python3 {BOT_SCRIPT}
            Restart=always
            RestartSec=10
            StandardOutput=journal
            StandardError=journal

            [Install]
            WantedBy=multi-user.target
        """)
        write_unit(BOT_SERVICE, unit, dry_run=self.dry_run)
        daemon_reload(dry_run=self.dry_run)
        enable_unit(BOT_SERVICE_NAME, dry_run=self.dry_run)
        start_unit(BOT_SERVICE_NAME, dry_run=self.dry_run)

        self.mark_done({"token_set": True, "chat_id": chat_id})
        return StepResult(
            self.name, True,
            "Telegram bot installed and started",
            "Send /start to your bot in Telegram to verify. Daily report at 08:00.\n"
            "Note: Immich commands require an API key — generate one in the\n"
            "Immich web UI (Settings → API Keys) and paste it into `homecloud` config.",
        )

    def _write_bot_script(self) -> None:
        """Write the full interactive bot script."""
        script = self._bot_template()
        if self.dry_run:
            self.log(f"[dry-run] would write {BOT_SCRIPT}")
            return
        write_file_sudo(BOT_SCRIPT, script, mode=0o755)
        self.log(f"Wrote {BOT_SCRIPT}")

    def _bot_template(self) -> str:
        return textwrap.dedent(f'''\
            #!/usr/bin/env python3
            """Home Cloud Telegram Bot — daily reports + on-demand commands.
            Queries the Immich REST API for storage stats, job status, etc.
            Generated by homecloud installer.
            """

            import os, re, subprocess, json, logging
            from datetime import datetime
            import requests
            from telegram import Update, BotCommand
            from telegram.ext import Application, CommandHandler, ContextTypes
            from apscheduler.schedulers.asyncio import AsyncIOScheduler

            TELEGRAM_TOKEN = "{self.cfg.telegram_bot_token}"
            CHAT_ID = "{self.cfg.telegram_chat_id}"
            # Use localhost, not the Tailscale HTTPS URL: the Pi runs with
            # --accept-dns=false and cannot resolve its own MagicDNS name.
            IMMICH_URL = "http://127.0.0.1:2283"
            IMMICH_API_KEY = "{self.cfg.immich_api_key}"
            BACKUP_LOG = "/var/log/homecloud-backup.log"
            IMMICH_DATA_PATH = "/mnt/data/immich"
            RESTIC_REPO = "{self.cfg.restic_repository}"
            AWS_KEY = "{self.cfg.aws_access_key_id}"
            AWS_SECRET = "{self.cfg.aws_secret_access_key}"
            RESTIC_PASSWORD = "{self.cfg.restic_password}"

            logging.basicConfig(level=logging.INFO)
            logger = logging.getLogger(__name__)

            def bytes_to_human(b):
                try: b = int(b)
                except: return str(b)
                for u in ["B","KB","MB","GB","TB"]:
                    if b < 1024: return f"{{b:.1f}} {{u}}"
                    b /= 1024
                return f"{{b:.1f}} PB"

            def run(cmd):
                try:
                    return subprocess.check_output(cmd, shell=True, stderr=subprocess.DEVNULL, text=True).strip()
                except: return "N/A"

            def immich_headers():
                return {{"x-api-key": IMMICH_API_KEY, "Accept": "application/json"}}

            def get_immich_stats():
                """Fetch server statistics from the Immich API."""
                if not IMMICH_API_KEY:
                    return None
                try:
                    r = requests.get(
                        f"{{IMMICH_URL}}/api/server/statistics",
                        headers=immich_headers(),
                        timeout=15,
                    )
                    r.raise_for_status()
                    return r.json()
                except Exception as e:
                    logger.error(f"Immich API error: {{e}}")
                    return None

            def get_immich_jobs():
                """Fetch job statuses from the Immich API."""
                if not IMMICH_API_KEY:
                    return None
                try:
                    r = requests.get(
                        f"{{IMMICH_URL}}/api/jobs",
                        headers=immich_headers(),
                        timeout=15,
                    )
                    r.raise_for_status()
                    return r.json()
                except Exception as e:
                    logger.error(f"Immich jobs API error: {{e}}")
                    return None

            def parse_backup_log():
                result = {{"last_run": "Never", "status": "Unknown", "uploaded": "N/A", "duration": "N/A"}}
                if not os.path.exists(BACKUP_LOG): return result
                with open(BACKUP_LOG) as f: lines = f.readlines()
                starts = [i for i,l in enumerate(lines) if "=== Backup started" in l]
                ends = [i for i,l in enumerate(lines) if "=== Backup finished" in l]
                if starts: result["last_run"] = lines[starts[-1]].replace("=== Backup started: ","").strip()
                errors = [l for l in lines[starts[-1]:] if "error" in l.lower()] if starts else []
                result["status"] = "❌ Error" if errors else "✅ Success"
                for line in reversed(lines):
                    if "Added to the repo" in line:
                        m = re.search(r"Added to the repo.*?:\\s*(.+)", line)
                        if m: result["uploaded"] = m.group(1).strip()
                        break
                return result

            def get_restic_snapshots():
                env = {{**os.environ, "AWS_ACCESS_KEY_ID": AWS_KEY,
                        "AWS_SECRET_ACCESS_KEY": AWS_SECRET,
                        "RESTIC_PASSWORD": RESTIC_PASSWORD,
                        "RESTIC_REPOSITORY": RESTIC_REPO}}
                try:
                    out = subprocess.check_output(
                        ["restic", "snapshots", "--compact", "--last", "5"],
                        env=env, stderr=subprocess.DEVNULL, text=True, timeout=30)
                    return out.strip()
                except: return "Could not reach S3 (Glacier restore may be needed)"

            def build_quick_status():
                uptime = run("uptime -p")
                cpu_temp = run("vcgencmd measure_temp | cut -d= -f2")
                mem = run("free -h | awk '/^Mem:/ {{print $3\\\"/\\\"$2}}'")
                cpu = run("top -bn1 | grep 'Cpu' | awk '{{print $2}}' | cut -d% -f1")
                ssd = run("df -h /mnt/data | awk 'NR==2 {{print $3\\\"/\\\"$2\\\" (\\\"$5\\\")\\\"}}'")
                immich_status = run("docker inspect --format='{{{{.State.Status}}}}' immich-server 2>/dev/null")
                bk = parse_backup_log()
                return (
                    f"⚡ *Quick Status*\\n"
                    f"🕐 {{datetime.now().strftime('%d %b %Y %H:%M')}}\\n\\n"
                    f"🖥 CPU: `{{cpu}}%` load | `{{cpu_temp}}` temp\\n"
                    f"🧠 RAM: `{{mem}}`\\n"
                    f"💾 SSD: `{{ssd}}`\\n"
                    f"📸 Immich: `{{immich_status}}`\\n\\n"
                    f"📦 Last backup: `{{bk['last_run']}}`\\n"
                    f"   Status: {{bk['status']}} | Uploaded: `{{bk['uploaded']}}`"
                )

            def build_daily_report():
                stats = get_immich_stats()
                jobs = get_immich_jobs()
                bk = parse_backup_log()
                uptime = run("uptime -p")
                cpu_temp = run("vcgencmd measure_temp | cut -d= -f2")
                mem = run("free -h | awk '/^Mem:/ {{print $3\\\"/\\\"$2}}'")
                cpu = run("top -bn1 | grep 'Cpu' | awk '{{print $2}}' | cut -d% -f1")
                ssd = run("df -h /mnt/data | awk 'NR==2 {{print $3\\\"/\\\"$2\\\" (\\\"$5\\\")\\\"}}'")
                sd = run("df -h / | awk 'NR==2 {{print $3\\\"/\\\"$2\\\" (\\\"$5\\\")\\\"}}'")
                immich_block = "❌ Immich API unavailable (set immich_api_key in config)"
                if stats:
                    immich_block = (
                        f"*Immich*\\n"
                        f"• Photos: `{{stats.get('photos', '?')}}`\\n"
                        f"• Videos: `{{stats.get('videos', '?')}}`\\n"
                        f"• Total usage: `{{bytes_to_human(stats.get('usage', 0))}}`"
                    )
                jobs_block = ""
                if jobs:
                    active = [name for name, info in jobs.items()
                              if isinstance(info, dict)
                              and isinstance(info.get("queueStatus"), dict)
                              and info["queueStatus"].get("isActive")]
                    if active:
                        jobs_block = f"\\n🔄 Active jobs: `{{', '.join(active)}}`"
                return (
                    f"📊 *Immich Daily Report*\\n"
                    f"📅 {{datetime.now().strftime('%A, %d %b %Y %H:%M')}}\\n\\n"
                    f"🏠 *System*\\n• Uptime: `{{uptime}}`\\n• CPU: `{{cpu}}%` | Temp: `{{cpu_temp}}`\\n"
                    f"• RAM: `{{mem}}`\\n• SSD: `{{ssd}}`\\n• SD: `{{sd}}`\\n\\n"
                    f"📸 {{immich_block}}{{jobs_block}}\\n\\n"
                    f"📦 *Backup*\\n• Last: `{{bk['last_run']}}`\\n• Status: {{bk['status']}}\\n"
                    f"• Uploaded: `{{bk['uploaded']}}`"
                )

            def build_backup_report():
                bk = parse_backup_log()
                snaps = get_restic_snapshots()
                tail = run(f"tail -20 {{BACKUP_LOG}} 2>/dev/null") or "No log yet"
                return (
                    f"📦 *Backup Deep Dive*\\n📅 {{datetime.now().strftime('%d %b %Y %H:%M')}}\\n\\n"
                    f"• Last run: `{{bk['last_run']}}`\\n• Status: {{bk['status']}}\\n"
                    f"• Uploaded: `{{bk['uploaded']}}`\\n\\n"
                    f"🗂 *S3 Snapshots*\\n```{{snaps}}```\\n\\n"
                    f"📋 *Log tail*\\n```{{tail[-600:]}}```"
                )

            def build_jobs_report():
                """Immich job statuses (library scan, face detection, ML, etc.)."""
                jobs = get_immich_jobs()
                if not jobs:
                    return "❌ Could not fetch Immich jobs (set immich_api_key in config)."
                lines = []
                for name, info in jobs.items():
                    if not isinstance(info, dict):
                        continue
                    qs = info.get("queueStatus", {{}})
                    if not isinstance(qs, dict):
                        qs = {{}}
                    jc = info.get("jobCounts", {{}})
                    if not isinstance(jc, dict):
                        jc = {{}}
                    is_paused = qs.get("isPaused", False)
                    is_active = qs.get("isActive", False)
                    active = jc.get("active", 0)
                    waiting = jc.get("waiting", 0)
                    icon = "🔄" if is_active else ("⏸" if is_paused else "✅")
                    lines.append(f"• {{icon}} `{{name}}`: {{active}} active, {{waiting}} waiting")
                return (
                    f"🔄 *Immich Jobs*\\n📅 {{datetime.now().strftime('%d %b %Y %H:%M')}}\\n\\n"
                    + "\\n".join(lines[:20])
                )

            async def cmd_start(update, ctx):
                await update.message.reply_text(
                    "👋 *Home Cloud Bot Online!*\\n\\n"
                    "/status — quick health check\\n"
                    "/report — full daily report\\n"
                    "/jobs — Immich job statuses\\n"
                    "/backup — backup status + S3 snapshots\\n"
                    "/runbackup — trigger a backup NOW\\n"
                    "/logs — last 30 lines of backup log\\n"
                    "/help — show this menu",
                    parse_mode="Markdown")

            async def cmd_status(update, ctx):
                await update.message.reply_text("⏳ Fetching...")
                try:
                    await update.message.reply_text(build_quick_status(), parse_mode="Markdown")
                except Exception as e:
                    logger.error(f"cmd_status error: {{e}}")
                    await update.message.reply_text(build_quick_status(), parse_mode=None)

            async def cmd_report(update, ctx):
                await update.message.reply_text("⏳ Building report...")
                try:
                    await update.message.reply_text(build_daily_report(), parse_mode="Markdown")
                except Exception as e:
                    logger.error(f"cmd_report error: {{e}}")
                    await update.message.reply_text(build_daily_report(), parse_mode=None)

            async def cmd_backup(update, ctx):
                await update.message.reply_text("⏳ Fetching backup details...")
                try:
                    await update.message.reply_text(build_backup_report(), parse_mode="Markdown")
                except Exception as e:
                    logger.error(f"cmd_backup error: {{e}}")
                    await update.message.reply_text(build_backup_report(), parse_mode=None)

            async def cmd_jobs(update, ctx):
                await update.message.reply_text("⏳ Fetching Immich jobs...")
                try:
                    await update.message.reply_text(build_jobs_report(), parse_mode="Markdown")
                except Exception as e:
                    logger.error(f"cmd_jobs error: {{e}}")
                    await update.message.reply_text(build_jobs_report(), parse_mode=None)

            async def cmd_runbackup(update, ctx):
                await update.message.reply_text("🚀 Triggering backup now...")
                try:
                    subprocess.Popen(
                        ["sudo", "/opt/homecloud-backup.sh"],
                        stdout=open(BACKUP_LOG, "a"), stderr=subprocess.STDOUT)
                    await update.message.reply_text("✅ Backup started! Check /backup in ~5 min.")
                except Exception as e:
                    logger.error(f"cmd_runbackup error: {{e}}")
                    await update.message.reply_text(f"❌ Failed to start backup: {{e}}")

            async def cmd_logs(update, ctx):
                log_content = run(f"tail -30 {{BACKUP_LOG}} 2>/dev/null") or "No log file yet"
                try:
                    await update.message.reply_text(f"📋 *Log*\\n```{{log_content[-2000:]}}```", parse_mode="Markdown")
                except Exception as e:
                    logger.error(f"cmd_logs error: {{e}}")
                    await update.message.reply_text(f"📋 Log:\\n{{log_content[-2000:]}}", parse_mode=None)

            async def cmd_help(update, ctx):
                await cmd_start(update, ctx)

            async def send_daily_report(app):
                try:
                    await app.bot.send_message(chat_id=CHAT_ID, text=build_daily_report(), parse_mode="Markdown")
                except Exception as e:
                    logger.error(f"Daily report failed: {{e}}")

            def main():
                app = Application.builder().token(TELEGRAM_TOKEN).build()
                app.add_handler(CommandHandler("start", cmd_start))
                app.add_handler(CommandHandler("status", cmd_status))
                app.add_handler(CommandHandler("report", cmd_report))
                app.add_handler(CommandHandler("jobs", cmd_jobs))
                app.add_handler(CommandHandler("backup", cmd_backup))
                app.add_handler(CommandHandler("runbackup", cmd_runbackup))
                app.add_handler(CommandHandler("logs", cmd_logs))
                app.add_handler(CommandHandler("help", cmd_help))

                async def post_init(application):
                    await application.bot.set_my_commands([
                        BotCommand("status", "⚡ Quick health check"),
                        BotCommand("report", "📊 Full daily report"),
                        BotCommand("jobs", "🔄 Immich job statuses"),
                        BotCommand("backup", "📦 Backup + S3 snapshots"),
                        BotCommand("runbackup", "🚀 Trigger backup now"),
                        BotCommand("logs", "📋 View backup log"),
                        BotCommand("help", "❓ Show all commands"),
                    ])
                    scheduler = AsyncIOScheduler(timezone="{self.cfg.timezone}")
                    scheduler.add_job(send_daily_report, trigger="cron", hour=8, minute=0, args=[application])
                    scheduler.start()

                app.post_init = post_init
                app.run_polling(allowed_updates=Update.ALL_TYPES)

            if __name__ == "__main__":
                main()
            ''')

    def status(self) -> StepResult:
        if self.dry_run:
            return StepResult(self.name, True, "[dry-run]")
        st = unit_status(BOT_SERVICE_NAME)
        return StepResult(self.name, st == "active", f"{BOT_SERVICE_NAME}: {st}")

    def repair(self) -> StepResult:
        self.log("Restarting bot service...")
        start_unit(BOT_SERVICE_NAME, dry_run=self.dry_run)
        return self.status()

    def undo(self) -> StepResult:
        self.log("Conservative undo: stopping + disabling bot (script kept)")
        stop_unit(BOT_SERVICE_NAME, dry_run=self.dry_run)
        disable_unit(BOT_SERVICE_NAME, dry_run=self.dry_run)
        if not self.dry_run and file_exists_sudo(BOT_SERVICE):
            run(f"sudo -n rm -f {BOT_SERVICE}", capture=True)
            daemon_reload(dry_run=self.dry_run)
        self.mark_undone()
        return StepResult(self.name, True, f"Bot service removed (script kept at {BOT_SCRIPT})")
